In [1]:
# importing libraries    
import numpy as nm    
import matplotlib.pyplot as mtp    
import pandas as pd   
from sklearn.cluster import DBSCAN
from numpy import unique
from numpy import where
from matplotlib import pyplot

In [2]:
# Importing the dataset  
dataset = pd.read_csv('data.csv')   
dataset.drop(dataset.index[dataset['game'] == 'Alternating'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Sustained'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Selective'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Divided'], inplace = True)

dataset.drop(dataset.index[dataset['child_age'] == 6], inplace = True)
dataset.drop(dataset.index[dataset['child_age'] == 7], inplace = True)

display(dataset)

id  child_gender  child_age  total_correct_responses  correct_responses  \
79    80             1          4                       10                 10   
80    81             1          4                       10                 10   
81    82             1          4                       10                 10   
82    83             2          4                       10                 10   
83    84             2          4                       10                  9   
84    85             2          4                       10                 10   
85    86             2          4                       10                  8   
86    87             2          4                       10                 10   
87    88             2          4                       10                  8   
88    89             2          4                       10                  9   
89    90             2          4                       10                 10   
90    91             1          4                       10                  9   
91    92             1          4                       10                 10   
92    93             1          4                       10                 10   
93    94             1          4                       10                 10   
94    95             1          4                       10                 10   
95    96             1          4                       10                 10   
96    97             1          4                       10                  9   
97    98             1          4                       10                 10   
98    99             1          4                       10                  9   
99   100             1          4                       10                  7   
100  101             1          4                       10                 10   
101  102             1          4                       10                 10   
102  103             1          4                       10                  9   
103  104             1          4                       10                  8   
104  105             1          4                       10                  7   
105  106             2          5                       12                 11   
106  107             2          5                       12                 11   
107  108             2          5                       12                 12   
108  109             2          5                       12                 12   
109  110             2          5                       12                 12   
110  111             2          5                       12                 12   
111  112             1          5                       12                 12   
112  113             1          5                       12                 12   
113  114             1          5                       12                 10   
114  115             2          5                       12                 10   
115  116             2          5                       12                 11   
116  117             2          5                       12                 12   
117  118             2          5                       12                 12   
118  119             2          5                       12                 12   
119  120             2          5                       12                 12   
120  121             2          5                       12                 12   
121  122             2          5                       12                 11   
122  123             2          5                       12                 12   
123  124             2          5                       12                 12   
124  125             2          5                       12                 10   
125  126             2          5                       12                 12   
126  127             2          5                       12                 12   
127  128             2          5    

In [3]:
# extracting only 11-comission & 12-omission
x = dataset.iloc[:, [7, 10, 11]].values  
display(x)

array([[1448.        ,  100.        ,    0.        ],
       [1331.        ,  100.        ,    0.        ],
       [1426.        ,  100.        ,    0.        ],
       [1632.        ,  100.        ,    0.        ],
       [1340.        ,   90.        ,   10.        ],
       [1564.        ,  100.        ,    0.        ],
       [1366.        ,   80.        ,   20.        ],
       [1291.        ,  100.        ,    0.        ],
       [2032.        ,   80.        ,   20.        ],
       [1789.        ,   90.        ,   10.        ],
       [1680.        ,  100.        ,    0.        ],
       [1317.        ,   90.        ,   10.        ],
       [1040.        ,  100.        ,    0.        ],
       [1142.        ,  100.        ,    0.        ],
       [1168.        ,  100.        ,    0.        ],
       [1150.        ,  100.        ,    0.        ],
       [1270.        ,  100.        ,    0.        ],
       [1457.        ,   90.        ,   10.        ],
       [1180.        ,  100.

In [4]:
# standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
new_df = scaler.fit_transform(x)

# statistics of scaled data
pd.DataFrame(new_df).describe()

display(new_df)


array([[ 0.08876077,  0.65810029, -0.65810029],
       [-0.35063754,  0.65810029, -0.65810029],
       [ 0.00613887,  0.65810029, -0.65810029],
       [ 0.77978033,  0.65810029, -0.65810029],
       [-0.31683767, -0.56408597,  0.56408597],
       [ 0.52440354,  0.65810029, -0.65810029],
       [-0.2191936 , -1.78627223,  1.78627223],
       [-0.50085918,  0.65810029, -0.65810029],
       [ 2.28199678, -1.78627223,  1.78627223],
       [ 1.36940029, -0.56408597,  0.56408597],
       [ 0.96004631,  0.65810029, -0.65810029],
       [-0.40321512, -0.56408597,  0.56408597],
       [-1.4435    ,  0.65810029, -0.65810029],
       [-1.06043481,  0.65810029, -0.65810029],
       [-0.96279074,  0.65810029, -0.65810029],
       [-1.03039048,  0.65810029, -0.65810029],
       [-0.57972555,  0.65810029, -0.65810029],
       [ 0.12256064, -0.56408597,  0.56408597],
       [-0.91772425,  0.65810029, -0.65810029],
       [-0.61352542, -0.56408597,  0.56408597],
       [-0.71492503, -3.00845849,  3.008

In [5]:
x = dataset.iloc[:, [2, 7, 10, 11]].copy()
x[['mean_reaction_time', 'percentage_no_of_correct_responses', 'oer']] = new_df
x.head()
x = x.to_numpy()
display(x)


array([[ 4.        ,  0.08876077,  0.65810029, -0.65810029],
       [ 4.        , -0.35063754,  0.65810029, -0.65810029],
       [ 4.        ,  0.00613887,  0.65810029, -0.65810029],
       [ 4.        ,  0.77978033,  0.65810029, -0.65810029],
       [ 4.        , -0.31683767, -0.56408597,  0.56408597],
       [ 4.        ,  0.52440354,  0.65810029, -0.65810029],
       [ 4.        , -0.2191936 , -1.78627223,  1.78627223],
       [ 4.        , -0.50085918,  0.65810029, -0.65810029],
       [ 4.        ,  2.28199678, -1.78627223,  1.78627223],
       [ 4.        ,  1.36940029, -0.56408597,  0.56408597],
       [ 4.        ,  0.96004631,  0.65810029, -0.65810029],
       [ 4.        , -0.40321512, -0.56408597,  0.56408597],
       [ 4.        , -1.4435    ,  0.65810029, -0.65810029],
       [ 4.        , -1.06043481,  0.65810029, -0.65810029],
       [ 4.        , -0.96279074,  0.65810029, -0.65810029],
       [ 4.        , -1.03039048,  0.65810029, -0.65810029],
       [ 4.        , -0.

In [16]:
from sklearn.cluster import Birch

# define the model
model = Birch(threshold=0.01, n_clusters=4)
# fit the model
model.fit(x)
# assign a cluster to each example
yhat = model.predict(x)
# retrieve unique clusters
clusters = unique(yhat)
print(clusters)

[0 1 2 3]


In [8]:
new_df = dataset.iloc[:, [2, 7, 10, 11]].copy()
new_df['clusters'] = yhat
new_df.head()
display(new_df)

child_age  mean_reaction_time  percentage_no_of_correct_responses  \
79           4                1448                          100.000000   
80           4                1331                          100.000000   
81           4                1426                          100.000000   
82           4                1632                          100.000000   
83           4                1340                           90.000000   
84           4                1564                          100.000000   
85           4                1366                           80.000000   
86           4                1291                          100.000000   
87           4                2032                           80.000000   
88           4                1789                           90.000000   
89           4                1680                          100.000000   
90           4                1317                           90.000000   
91           4                1040                          100.000000   
92           4                1142                          100.000000   
93           4                1168                          100.000000   
94           4                1150                          100.000000   
95           4                1270                          100.000000   
96           4                1457                           90.000000   
97           4                1180                          100.000000   
98           4                1261                           90.000000   
99           4                1234                           70.000000   
100          4                1165                          100.000000   
101          4                1238                          100.000000   
102          4                1830                           90.000000   
103          4                1657                           80.000000   
104          4                1817                           70.000000   
105          5                1600                           91.666667   
106          5                1396                           91.666667   
107          5                1380                          100.000000   
108          5                1350                          100.000000   
109          5                1310                          100.000000   
110          5                1462                          100.000000   
111          5                1069                          100.000000   
112          5                1221                          100.000000   
113          5                1775                           83.333333   
114          5                1852                           83.333333   
115          5                1598                           91.666667   
116          5                1785                          100.000000   
117          5                1628                          100.000000   
118          5                1758                          100.000000   
119          5                1215                          100.000000   
120          5                1134                          100.000000   
121          5                1364                           91.666667   
122          5                1499                          100.000000   
123          5                1998                          100.000000   
124          5                1916                           83.333333   
125          5                1152                          100.000000   
126          5                1086                          100.000000   
127          5                1207                          100.000000   
128          5                1047                          100.000000   
129          5                1162                           83.333333   
130          5                1278                          100.000000   

           oer  clusters  
79    0.000000         2  
80    0.000000         2  
8

In [9]:
from sklearn.metrics import silhouette_score,calinski_harabasz_score,davies_bouldin_score

print("Silhouette Coefficient: %0.3f" % silhouette_score(x, yhat))
print("Calinski-Harabasz Index: %0.3f" % calinski_harabasz_score(x, yhat))
print("Davies-Bouldin Index: %0.3f" % davies_bouldin_score(x, yhat))

Silhouette Coefficient: 0.401
Calinski-Harabasz Index: 41.707
Davies-Bouldin Index: 0.932


# Cluster Analysis

## Cluster 1

In [10]:
len(new_df[new_df["clusters"] == 0])

11

In [11]:
cluster_0 = new_df[new_df["clusters"] == 0 ]
display(cluster_0)

child_age  mean_reaction_time  percentage_no_of_correct_responses  \
85           4                1366                           80.000000   
87           4                2032                           80.000000   
88           4                1789                           90.000000   
99           4                1234                           70.000000   
102          4                1830                           90.000000   
103          4                1657                           80.000000   
104          4                1817                           70.000000   
113          5                1775                           83.333333   
114          5                1852                           83.333333   
124          5                1916                           83.333333   
129          5                1162                           83.333333   

           oer  clusters  
85   20.000000         0  
87   20.000000         0  
88   10.000000         0  
99   30.000000         0  
102  10.000000         0  
103  20.000000         0  
104  30.000000         0  
113  16.666667         0  
114  16.666667         0  
124  16.666667         0  
129  16.666667         0

In [12]:
cluster_0 = new_df[new_df["clusters"] == 0 ]

maxVal = cluster_0['mean_reaction_time'].max()
minVal = cluster_0['mean_reaction_time'].min()

print("mean_reaction_time min - ", minVal)
print("mean_reaction_time max - ", maxVal)
print()

maxVal = cluster_0['percentage_no_of_correct_responses'].max()
minVal = cluster_0['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_0['oer'].max()
minVal = cluster_0['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)

mean_reaction_time min -  1162
mean_reaction_time max -  2032

percentage_no_of_correct_responses min -  70.0
percentage_no_of_correct_responses max -  90.0

oer min -  10.0
oer max -  30.0


## Cluster 2

In [13]:
len(new_df[new_df["clusters"] == 1])

7

In [14]:
cluster_1 = new_df[new_df["clusters"] == 1 ]
display(cluster_1)

child_age  mean_reaction_time  percentage_no_of_correct_responses  oer  \
82           4                1632                               100.0  0.0   
84           4                1564                               100.0  0.0   
89           4                1680                               100.0  0.0   
116          5                1785                               100.0  0.0   
117          5                1628                               100.0  0.0   
118          5                1758                               100.0  0.0   
123          5                1998                               100.0  0.0   

     clusters  
82          1  
84          1  
89          1  
116         1  
117         1  
118         1  
123         1

In [15]:
cluster_1 = new_df[new_df["clusters"] == 1 ]

maxVal = cluster_1['mean_reaction_time'].max()
minVal = cluster_1['mean_reaction_time'].min()

print("mean_reaction_time min - ", minVal)
print("mean_reaction_time max - ", maxVal)
print()

maxVal = cluster_1['percentage_no_of_correct_responses'].max()
minVal = cluster_1['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_1['oer'].max()
minVal = cluster_1['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)

mean_reaction_time min -  1564
mean_reaction_time max -  1998

percentage_no_of_correct_responses min -  100.0
percentage_no_of_correct_responses max -  100.0

oer min -  0.0
oer max -  0.0
