In [1]:
# importing libraries    
import numpy as nm    
import matplotlib.pyplot as mtp    
import pandas as pd   
from sklearn.cluster import DBSCAN
from numpy import unique
from numpy import where
from matplotlib import pyplot

In [2]:
# Importing the dataset  
dataset = pd.read_csv('data.csv')   
dataset.drop(dataset.index[dataset['game'] == 'Alternating'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Sustained'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Focused'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Divided'], inplace = True)
display(dataset)

id  child_gender  child_age  total_correct_responses  correct_responses  \
160  161             1          4                        8                  8   
161  162             2          4                        6                  6   
162  163             2          4                        6                  6   
163  164             2          4                        6                  6   
164  165             2          4                        7                  6   
..   ...           ...        ...                      ...                ...   
319  320             1          7                        8                  8   
320  321             1          7                        6                  0   
321  322             1          7                        7                  5   
322  323             1          7                        7                  7   
323  324             1          7                        6                  6   

     commission_errors  omission_errors  mean_reaction_time  total_duration  \
160                  0                0                   0            3459   
161                  0                0                   0            3000   
162                  0                0                   0           10888   
163                  0                0                   0            7081   
164                  0                1                   0            9953   
..                 ...              ...                 ...             ...   
319                  0                0                   0           12332   
320                  3                6                   0            8190   
321                  0                2                   0            6749   
322                  0                0                   0            7795   
323                  0                0                   0           14779   

    diagnosis  percentage_no_of_correct_responses         oer   cer       game  
160        No                          100.000000    0.000000   0.0  Selective  
161        No                          100.000000    0.000000   0.0  Selective  
162        No                          100.000000    0.000000   0.0  Selective  
163        No                          100.000000    0.000000   0.0  Selective  
164        No                           85.714286   14.285714   0.0  Selective  
..        ...                                 ...         ...   ...        ...  
319        No                          100.000000    0.000000   0.0  Selective  
320        No                            0.000000  100.000000  50.0  Selective  
321        No                           71.428571   28.571429   0.0  Selective  
322        No                          100.000000    0.000000   0.0  Selective  
323        No                          100.000000    0.000000   0.0  Selective  

[164 rows x 14 columns]

In [3]:
# extracting only 11-comission & 12-omission
x = dataset.iloc[:, [8, 10, 11, 12]].values  
display(x)

array([[3.45900000e+03, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [3.00000000e+03, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [1.08880000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [7.08100000e+03, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [9.95300000e+03, 8.57142857e+01, 1.42857143e+01, 0.00000000e+00],
       [1.42070000e+04, 1.00000000e+02, 0.00000000e+00, 2.22222222e+01],
       [1.40360000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [1.26460000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [7.25100000e+03, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [1.00260000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [1.14820000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [1.20860000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [1.08160000e+04, 1.00000000e+02, 0.00000000e+00, 0.00000000e+00],
       [6.34500000e+03, 1.00000000e+02, 0.00000000e

In [4]:
# standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
new_df = scaler.fit_transform(x)

# statistics of scaled data
pd.DataFrame(new_df).describe()

display(new_df)


array([[-1.42198814e+00,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-1.49278251e+00,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-2.76168192e-01,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-8.63345004e-01,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-4.20378940e-01, -4.17936084e-01,  4.17936084e-01,
        -3.16765400e-01],
       [ 2.35741406e-01,  3.68015386e-01, -3.68015386e-01,
         1.42682072e+00],
       [ 2.09367034e-01,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-5.02113725e-03,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-8.37124867e-01,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-4.09119705e-01,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-1.84551951e-01,  3.68015386e-01, -3.68015386e-01,
        -3.16765400e-01],
       [-9.13933502e-02,  3.68015386e-01, -3.68015386e-01,
      

In [5]:
x = dataset.iloc[:, [2, 8, 10, 11, 12]].copy()
x[['total_duration', 'percentage_no_of_correct_responses', 'oer', 'cer']] = new_df
x.head()
x = x.to_numpy()
display(x)


array([[ 4.00000000e+00, -1.42198814e+00,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -1.49278251e+00,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -2.76168192e-01,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -8.63345004e-01,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -4.20378940e-01, -4.17936084e-01,
         4.17936084e-01, -3.16765400e-01],
       [ 4.00000000e+00,  2.35741406e-01,  3.68015386e-01,
        -3.68015386e-01,  1.42682072e+00],
       [ 4.00000000e+00,  2.09367034e-01,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -5.02113725e-03,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -8.37124867e-01,  3.68015386e-01,
        -3.68015386e-01, -3.16765400e-01],
       [ 4.00000000e+00, -4.09119705e-01,  3.68015386e-01,
        -3.68015386e-01

In [6]:
from sklearn.datasets import make_classification
from sklearn.cluster import MeanShift

# define the model
model = MeanShift()
# fit model and predict clusters
yhat = model.fit_predict(x)
# retrieve unique clusters
clusters = unique(yhat)

In [7]:
ms = MeanShift()
ms.fit(x)
labels = ms.labels_
cluster_centers = ms.cluster_centers_
print(cluster_centers)
n_clusters_ = len(nm.unique(labels))
print("Estimated clusters:", n_clusters_)

[[ 4.79279279 -0.17014686  0.27567199 -0.27567199 -0.19713228]
 [ 4.4        -0.60311786 -3.52899399  3.52899399 -0.3167654 ]
 [ 4.          1.11920576  0.36801539 -0.36801539  5.10080575]
 [ 7.          5.42146738  0.36801539 -0.36801539  4.16674176]
 [ 7.          1.69820806 -0.548928    0.548928    2.29861377]
 [ 7.          0.26643439 -4.21670152  4.21670152 -0.3167654 ]
 [ 7.         -0.69229717 -5.13364491  5.13364491  3.60630336]
 [ 6.         -0.66453468 -4.21670152  4.21670152  0.99092419]
 [ 6.         -0.99891853 -1.46587138  1.46587138  2.29861377]
 [ 5.          5.82741678  0.36801539 -0.36801539 -0.3167654 ]
 [ 5.          4.55311817  0.36801539 -0.36801539  6.22168254]]
Estimated clusters: 11


In [8]:
new_df = dataset.iloc[:, [2, 8, 10, 11, 12]].copy()
new_df['clusters'] = yhat
new_df.head()
display(new_df)

child_age  total_duration  percentage_no_of_correct_responses  \
160          4            3459                          100.000000   
161          4            3000                          100.000000   
162          4           10888                          100.000000   
163          4            7081                          100.000000   
164          4            9953                           85.714286   
..         ...             ...                                 ...   
319          7           12332                          100.000000   
320          7            8190                            0.000000   
321          7            6749                           71.428571   
322          7            7795                          100.000000   
323          7           14779                          100.000000   

            oer   cer  clusters  
160    0.000000   0.0         0  
161    0.000000   0.0         0  
162    0.000000   0.0         0  
163    0.000000   0.0         0  
164   14.285714   0.0         0  
..          ...   ...       ...  
319    0.000000   0.0         0  
320  100.000000  50.0         6  
321   28.571429   0.0         8  
322    0.000000   0.0         0  
323    0.000000   0.0         0  

[164 rows x 6 columns]

In [9]:
from sklearn.metrics import silhouette_score,calinski_harabasz_score,davies_bouldin_score

print("Silhouette Coefficient: %0.3f" % silhouette_score(x, yhat))
print("Calinski-Harabasz Index: %0.3f" % calinski_harabasz_score(x, yhat))
print("Davies-Bouldin Index: %0.3f" % davies_bouldin_score(x, yhat))

Silhouette Coefficient: 0.416
Calinski-Harabasz Index: 27.590
Davies-Bouldin Index: 0.519


# Cluster Analysis

## Cluster 1

In [10]:
len(new_df[new_df["clusters"] == 0])

145

In [11]:
cluster_0 = new_df[new_df["clusters"] == 0 ]
display(cluster_0)
# cluster_0.boxplot(column =['CER'], grid = False)
# cluster_0.boxplot(column =['OER'], grid = False)

child_age  total_duration  percentage_no_of_correct_responses        oer  \
160          4            3459                          100.000000   0.000000   
161          4            3000                          100.000000   0.000000   
162          4           10888                          100.000000   0.000000   
163          4            7081                          100.000000   0.000000   
164          4            9953                           85.714286  14.285714   
..         ...             ...                                 ...        ...   
316          7            7349                          100.000000   0.000000   
318          7            9166                          100.000000   0.000000   
319          7           12332                          100.000000   0.000000   
322          7            7795                          100.000000   0.000000   
323          7           14779                          100.000000   0.000000   

     cer  clusters  
160  0.0         0  
161  0.0         0  
162  0.0         0  
163  0.0         0  
164  0.0         0  
..   ...       ...  
316  0.0         0  
318  0.0         0  
319  0.0         0  
322  0.0         0  
323  0.0         0  

[145 rows x 6 columns]

In [12]:
cluster_0 = new_df[new_df["clusters"] == 0 ]

maxVal = cluster_0['total_duration'].max()
minVal = cluster_0['total_duration'].min()

print("total_duration min - ", minVal)
print("total_duration max - ", maxVal)
print()

maxVal = cluster_0['percentage_no_of_correct_responses'].max()
minVal = cluster_0['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_0['oer'].max()
minVal = cluster_0['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)
print()

maxVal = cluster_0['cer'].max()
minVal = cluster_0['cer'].min()

print("cer min - ", minVal)
print("cer max - ", maxVal)

total_duration min -  3000
total_duration max -  30387

percentage_no_of_correct_responses min -  66.66666667
percentage_no_of_correct_responses max -  100.0

oer min -  0.0
oer max -  33.33333333

cer min -  0.0
cer max -  22.22222222


## Cluster 2

In [13]:
len(new_df[new_df["clusters"] == 1])

6

In [14]:
cluster_1 = new_df[new_df["clusters"] == 1 ]
display(cluster_1)
#cluster_1.boxplot(column =['CER'], grid = False)
#cluster_1.boxplot(column =['OER'], grid = False)

child_age  total_duration  percentage_no_of_correct_responses        oer  \
177          4           10348                           12.500000  87.500000   
183          4           11724                           33.333333  66.666667   
194          4            6276                           16.666667  83.333333   
257          5            5112                           33.333333  66.666667   
268          5           10381                           50.000000  50.000000   
271          6           19055                           50.000000  50.000000   

     cer  clusters  
177  0.0         1  
183  0.0         1  
194  0.0         1  
257  0.0         1  
268  0.0         1  
271  0.0         1

In [15]:
cluster_1 = new_df[new_df["clusters"] == 1 ]

maxVal = cluster_1['total_duration'].max()
minVal = cluster_1['total_duration'].min()

print("total_duration min - ", minVal)
print("total_duration max - ", maxVal)
print()

maxVal = cluster_1['percentage_no_of_correct_responses'].max()
minVal = cluster_1['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_1['oer'].max()
minVal = cluster_1['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)
print()

maxVal = cluster_1['cer'].max()
minVal = cluster_1['cer'].min()

print("cer min - ", minVal)
print("cer max - ", maxVal)

total_duration min -  5112
total_duration max -  19055

percentage_no_of_correct_responses min -  12.5
percentage_no_of_correct_responses max -  50.0

oer min -  50.0
oer max -  87.5

cer min -  0.0
cer max -  0.0


## Cluster 3

In [16]:
len(new_df[new_df["clusters"] == 2])

3

In [17]:
cluster_2 = new_df[new_df["clusters"] == 2 ]
display(cluster_2)
#cluster_2.boxplot(column =['CER'], grid = False)
#cluster_2.boxplot(column =['OER'], grid = False)

child_age  total_duration  percentage_no_of_correct_responses  oer  \
182          4           22296                               100.0  0.0   
191          4           17495                               100.0  0.0   
210          4           22375                               100.0  0.0   

           cer  clusters  
182  33.333333         2  
191  71.428571         2  
210  66.666667         2

In [18]:
cluster_2 = new_df[new_df["clusters"] == 2 ]

maxVal = cluster_2['total_duration'].max()
minVal = cluster_2['total_duration'].min()

print("total_duration min - ", minVal)
print("total_duration max - ", maxVal)
print()

maxVal = cluster_2['percentage_no_of_correct_responses'].max()
minVal = cluster_2['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_2['oer'].max()
minVal = cluster_2['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)
print()

maxVal = cluster_2['cer'].max()
minVal = cluster_2['cer'].min()

print("cer min - ", minVal)
print("cer max - ", maxVal)

total_duration min -  17495
total_duration max -  22375

percentage_no_of_correct_responses min -  100.0
percentage_no_of_correct_responses max -  100.0

oer min -  0.0
oer max -  0.0

cer min -  33.33333333
cer max -  71.42857143


## Cluster 3

In [19]:
len(new_df[new_df["clusters"] == 3])

1

In [20]:
cluster_3 = new_df[new_df["clusters"] == 3 ]
display(cluster_3)
#cluster_2.boxplot(column =['CER'], grid = False)
#cluster_2.boxplot(column =['OER'], grid = False)

child_age  total_duration  percentage_no_of_correct_responses  oer  \
300          7           47829                               100.0  0.0   

           cer  clusters  
300  57.142857         3

In [21]:
cluster_3 = new_df[new_df["clusters"] == 3 ]

maxVal = cluster_3['total_duration'].max()
minVal = cluster_3['total_duration'].min()

print("total_duration min - ", minVal)
print("total_duration max - ", maxVal)
print()

maxVal = cluster_3['percentage_no_of_correct_responses'].max()
minVal = cluster_3['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_3['oer'].max()
minVal = cluster_3['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)
print()

maxVal = cluster_3['cer'].max()
minVal = cluster_3['cer'].min()

print("cer min - ", minVal)
print("cer max - ", maxVal)

total_duration min -  47829
total_duration max -  47829

percentage_no_of_correct_responses min -  100.0
percentage_no_of_correct_responses max -  100.0

oer min -  0.0
oer max -  0.0

cer min -  57.14285714
cer max -  57.14285714


In [22]:
len(new_df[new_df["clusters"] == -1])

0

In [23]:
outliers = new_df[new_df["clusters"] == -1 ]
display(outliers)

Empty DataFrame
Columns: [child_age, total_duration, percentage_no_of_correct_responses, oer, cer, clusters]
Index: []